### ISSUE TITLE
Additional functionality? 

### ISSUE THREAD

**Issue by RA2user** [senorshaun/homebridge-radiora2#13]
What a great plugin! I especially appreciate HVAC controls which otherwise are not available in Homekit. I was wondering whether it would be possible to add a fan-only mode (circulating the air w/o heating or cooling it). For example, Ecobee has a mode to circulate the air for X minutes every hour. It appears that for passing the air through a high efficiency filter to catch viruses and such is not a bad idea... Thank you.

**Comment by senorshaun** [comment]
I get what you're saying, I use ecobee at my house. But HomeKit itself doesn't expose a 'fan only' mode for thermostats. Nor do HomeKit enabled thermostats have a child accessory with a fan switch. I don't know that I want to start messing with that part, and exposing a separate fan switch to enable the fan can have its own issues. as the 'mode' of the thermostat in HomeKit would not match reality when switching over to 'fan only' mode. 

I dont have the touchpro I used for testing, but I think you can put the fan in to circ mode, rather than auto. It should run randomly, for 21 minutes an hour, plus when actively heating and cooling.

**Comment by RA2user** [comment]
I see. I have an old Lutron thermostat that has two modes: Auto and on. The latter appears to run the fan all the time rather than intermittently. But I may be wrong, will test. Thank you.
