### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by scott-hpe** [senorshaun/homebridge-radiora2#21]
In the RadioRA2 software we can define different button types on phantom keypads to create scenes. These currently get exposed to HomeKit as a switches. Can an option be defined to expose keypad buttons as scenes in HomeKit?

**Comment by senorshaun** [comment]
I don't believe homebridge plugins can create HomeKit scenes. I think those are only created manually via the home app. So theoretically you could create a scene for each switch, and the scene would status with the switch. but can I ask why you would want to have them show as scenes? There may be another way to do what you're wanting

**Comment by scott-hpe** [comment]
Yup. I was just looking on developers.homebridge.io and didn't seen anything about Scenes. 

As an example where a scene makes more sense, I have a scene in RadioRA2 defined for Morning and exported to HomeKit as a switch. Siri treats this as a switch (Siri, turn on Morning) instead of a scene. It also doesn't get a scene button in the Home app on the Home Screen but instead gets placed down with the other favorites. 

Again, it's possible to work around these things with the room full of switches that map to scenes. Just thinking it would have been cleaner without the switch to scene mapping.

**Comment by senorshaun** [comment]
Its a switch because you are only turning on Lutron Morning. I have something similar. I have a Evening Lighting scene in Lutron, that is exposed to HomeKit as a switch. I then have an Evening Lighting scene in HomeKit that turns on that switch, but also turns on some plugs that I have lamps, cabinet lights, armoires, etc plugged in to around the house. That scene controls lots of accessories whereas the Lutron evening lighting, though it controls lots of physical lights, is only one accessory. Just a quirk when you have two different things doing 'scenes'. 

Is it just aesthetics that you want Morning as a Scene rather than an switch (which you could display as a Light rather than a Switch).
